[project]
name = "software-engineering-uark"
version = "0.1.0"
description = "Software Engineering Project for the University of Arkansas"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "psycopg2-binary>=2.9.11",
    "pyside6==6.8.0.2",
]
